#!/bin/bash
# Deploy prediction market contracts to Stellar Testnet
# Run from: soroban-hello-world/stellar/
#
# Deployment order matters:
#   1. Generate + fund deployer identity
#   2. Upload prediction-market WASM → get wasm hash
#   3. Deploy market-factory → get factory address
#   4. Initialize factory with (admin, wasm_hash)
#   5. Wrap native XLM SAC → get token address
#
# Output: all addresses/hashes printed and saved to .env.deploy

set -euo pipefail

NETWORK="testnet"
RPC_URL="https://soroban-testnet.stellar.org"
NETWORK_PASSPHRASE="Test SDF Network ; September 2015"
IDENTITY="oracle-deployer"

echo "═══════════════════════════════════════════════════"
echo "  Stellar Prediction Market — Contract Deployment"
echo "═══════════════════════════════════════════════════"
echo ""

# ─────────────────────────────────────────────────────
# Step 1: Generate identity (or reuse existing)
# ─────────────────────────────────────────────────────
if stellar keys address "$IDENTITY" &>/dev/null; then
  echo "✅ Identity '$IDENTITY' already exists"
else
  echo "🔑 Generating new identity: $IDENTITY"
  stellar keys generate "$IDENTITY" --network "$NETWORK"
  echo "✅ Identity created"
fi

ADMIN_ADDRESS=$(stellar keys address "$IDENTITY")
echo "   Address: $ADMIN_ADDRESS"

# Fund via friendbot
echo "💰 Funding via friendbot..."
curl -s "https://friendbot.stellar.org?addr=$ADMIN_ADDRESS" > /dev/null 2>&1 || true
echo "✅ Account funded"
echo ""

# ─────────────────────────────────────────────────────
# Step 2: Build contracts (ensure up to date)
# ─────────────────────────────────────────────────────
echo "🔨 Building contracts..."
stellar contract build
echo "✅ Contracts built"
echo ""

# ─────────────────────────────────────────────────────
# Step 3: Upload prediction-market WASM → get hash
# ─────────────────────────────────────────────────────
echo "📤 Uploading prediction-market WASM..."
PM_WASM_HASH=$(stellar contract upload \
  --wasm target/wasm32v1-none/release/prediction_market.wasm \
  --source "$IDENTITY" \
  --rpc-url "$RPC_URL" \
  --network-passphrase "$NETWORK_PASSPHRASE")

echo "✅ Prediction Market WASM Hash: $PM_WASM_HASH"
echo ""

# ─────────────────────────────────────────────────────
# Step 4: Deploy market-factory contract
# ─────────────────────────────────────────────────────
echo "🚀 Deploying market-factory contract..."
FACTORY_ADDRESS=$(stellar contract deploy \
  --wasm target/wasm32v1-none/release/market_factory.wasm \
  --source "$IDENTITY" \
  --rpc-url "$RPC_URL" \
  --network-passphrase "$NETWORK_PASSPHRASE")

echo "✅ Factory Contract Address: $FACTORY_ADDRESS"
echo ""

# ─────────────────────────────────────────────────────
# Step 5: Initialize the factory
# ─────────────────────────────────────────────────────
echo "⚙️  Initializing factory..."
stellar contract invoke \
  --id "$FACTORY_ADDRESS" \
  --source "$IDENTITY" \
  --rpc-url "$RPC_URL" \
  --network-passphrase "$NETWORK_PASSPHRASE" \
  -- \
  init \
  --admin "$ADMIN_ADDRESS" \
  --market_wasm_hash "$PM_WASM_HASH"

echo "✅ Factory initialized with admin + prediction-market WASM"
echo ""

# ─────────────────────────────────────────────────────
# Step 6: Get the native XLM SAC (Stellar Asset Contract) address
# ─────────────────────────────────────────────────────
echo "🪙  Resolving native XLM SAC address..."
TOKEN_ADDRESS=$(stellar contract id asset \
  --asset native \
  --rpc-url "$RPC_URL" \
  --network-passphrase "$NETWORK_PASSPHRASE")

echo "✅ Native XLM SAC Address: $TOKEN_ADDRESS"
echo ""

# ─────────────────────────────────────────────────────
# Step 7: Get the oracle secret key for .env
# ─────────────────────────────────────────────────────
ORACLE_SECRET=$(stellar keys show "$IDENTITY")

# ─────────────────────────────────────────────────────
# Output summary
# ─────────────────────────────────────────────────────
echo "═══════════════════════════════════════════════════"
echo "  DEPLOYMENT COMPLETE — Copy these to your .env"
echo "═══════════════════════════════════════════════════"
echo ""
echo "STELLAR_NETWORK=testnet"
echo "STELLAR_RPC_URL=$RPC_URL"
echo "STELLAR_HORIZON_URL=https://horizon-testnet.stellar.org"
echo "STELLAR_NETWORK_PASSPHRASE=$NETWORK_PASSPHRASE"
echo "FACTORY_CONTRACT_ADDRESS=$FACTORY_ADDRESS"
echo "TOKEN_CONTRACT_ADDRESS=$TOKEN_ADDRESS"
echo "ORACLE_SECRET_KEY=$ORACLE_SECRET"
echo "ORACLE_PUBLIC_KEY=$ADMIN_ADDRESS"
echo ""

# Save to file for easy sourcing
cat > .env.deploy <<EOF
# Generated by deploy.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
STELLAR_NETWORK=testnet
STELLAR_RPC_URL=$RPC_URL
STELLAR_HORIZON_URL=https://horizon-testnet.stellar.org
STELLAR_NETWORK_PASSPHRASE=$NETWORK_PASSPHRASE
FACTORY_CONTRACT_ADDRESS=$FACTORY_ADDRESS
TOKEN_CONTRACT_ADDRESS=$TOKEN_ADDRESS
ORACLE_SECRET_KEY=$ORACLE_SECRET
ORACLE_PUBLIC_KEY=$ADMIN_ADDRESS
PM_WASM_HASH=$PM_WASM_HASH
EOF

echo "📁 Saved to stellar/.env.deploy"
echo ""
echo "Next steps:"
echo "  1. Copy the values above into your root .env file"
echo "  2. Start the backend: npm run dev"
echo "  3. Run the test script: npx ts-node src/scripts/testAPI.ts"
